#!/bin/bash
set -euo pipefail

EXTENDED_COPY=false
if [ "$#" -eq 1 ] && [ "$1" = "--extended-copy" ]; then
    EXTENDED_COPY=true
elif [ "$#" -ne 0 ]; then
    echo "[ERROR] Unknown arguments. Usage: $0 [--extended-copy]" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MIXXX_DIRS=(
    "${HOME}/.mixxx"
    "${HOME}/.mixxx-test"
)

link_file() {
    local src="$1"
    local target="$2"

    if [ -L "$target" ]; then
        rm -f "$target"
    elif [ -e "$target" ]; then
        echo "[WARN] Existing file or directory left unchanged: $target" >&2
        return
    fi

    ln -s "$src" "$target"
    echo "Linked: $target -> $src"
}

link_tree() {
    local src="$1"
    local dst="$2"

    mkdir -p "$dst"

    for entry in "$src"/*; do
        [ -e "$entry" ] || continue

        local target="${dst}/$(basename "$entry")"

        if [ -d "$entry" ]; then
            if [ -e "$target" ] && [ ! -d "$target" ]; then
                echo "[WARN] Existing file blocks directory; left unchanged: $target" >&2
                continue
            fi
            link_tree "$entry" "$target"
        else
            link_file "$entry" "$target"
        fi
    done
}

link_into_mixxx_dirs() {
    local name="$1"
    local src="${SCRIPT_DIR}/${name}"

    [ -d "$src" ] || return

    for base in "${MIXXX_DIRS[@]}"; do
        local dst="${base}/${name}"
        link_tree "$src" "$dst"
    done
}

link_into_mixxx_dirs "controllers"
link_into_mixxx_dirs "effects"

if [ "$EXTENDED_COPY" = true ]; then
    python3 - "$SCRIPT_DIR" "${MIXXX_DIRS[@]}" <<'PY'
import os
from pathlib import Path
import sys
import tempfile
import xml.etree.ElementTree as ET

source_dir = Path(sys.argv[1]) / "controllers"
basic_xml = "Pioneer-DDJ-FLX4-2.0.midi.xml"
basic_script = "Pioneer-DDJ-FLX4-2.0.script.js"
extended_script = "Pioneer-DDJ-FLX4-extended-scripts.js"
extended_xml = "Pioneer-DDJ-FLX4-2.0-Extended.midi.xml"
header = (
    b'<?xml version="1.0" encoding="UTF-8"?>\n'
    b'<!-- Generated by setup-mixxx-links.sh: extended-copy v1. '
    b'Local edits are replaced when regenerated. -->\n'
)

try:
    for filename in (basic_xml, basic_script, extended_script):
        if not (source_dir / filename).is_file():
            raise ValueError(f"Missing source file: {source_dir / filename}")

    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
    root = ET.parse(source_dir / basic_xml, parser=parser).getroot()
    names = root.findall("./info/name")
    controllers = root.findall("controller")
    scriptfiles = root.findall("./controller/scriptfiles")
    if (root.tag != "MixxxControllerPreset" or len(names) != 1
            or names[0].text != "Pioneer DDJ-FLX4 (Basic)"
            or len(controllers) != 1 or len(scriptfiles) != 1):
        raise ValueError("Unexpected Basic XML structure: expected one Basic name, "
                         "controller and scriptfiles block")
    scripts = [child for child in scriptfiles[0] if child.tag is not ET.Comment]
    if (len(scripts) != 1 or scripts[0].tag != "file"
            or scripts[0].get("filename") != basic_script
            or scripts[0].get("functionprefix") != "PioneerDDJFLX4"):
        raise ValueError("Unexpected Basic XML scriptfiles: expected only the Basic "
                         "script with functionprefix=\"PioneerDDJFLX4\"")

    names[0].text = "Pioneer DDJ-FLX4 (Extended)"
    extended = ET.Element("file", filename=extended_script, functionprefix="")
    extended.tail = scripts[0].tail
    scripts[0].tail = scriptfiles[0].text
    scriptfiles[0].insert(list(scriptfiles[0]).index(scripts[0]) + 1, extended)
    content = header + ET.tostring(root, encoding="utf-8") + b"\n"
    ET.fromstring(content)

    targets = [Path(base) / "controllers" / extended_xml for base in sys.argv[2:]]
    # Check both profiles before replacing either generated copy.
    for target in targets:
        if target.is_symlink():
            raise ValueError(f"Existing symlink left unchanged: {target}")
        if target.exists():
            if not target.is_file():
                raise ValueError(f"Existing directory or special file left unchanged: {target}")
            with target.open("rb") as existing:
                if existing.read(len(header)) != header:
                    raise ValueError(f"Existing foreign file left unchanged: {target}")

    for target in targets:
        # Replace atomically so an interrupted write leaves the previous copy intact.
        with tempfile.NamedTemporaryFile(dir=target.parent, delete=False) as output:
            temporary = Path(output.name)
            try:
                output.write(content)
                output.close()
                os.replace(temporary, target)
            finally:
                temporary.unlink(missing_ok=True)
        print(f"Generated: {target}")
except (OSError, ValueError, ET.ParseError) as error:
    sys.exit(f"[ERROR] Extended copy: {error}")
PY
fi

echo "Fertig."
