"""Run with: python3 tests/test_setup_mixxx_links.py (uses temporary profiles only)."""

import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
import xml.etree.ElementTree as ET


REPO = Path(__file__).resolve().parents[1]
BASIC_XML = "Pioneer-DDJ-FLX4-2.0.midi.xml"
BASIC_SCRIPT = "Pioneer-DDJ-FLX4-2.0.script.js"
EXTENDED_XML = "Pioneer-DDJ-FLX4-2.0-Extended.midi.xml"
EXTENDED_SCRIPT = "Pioneer-DDJ-FLX4-extended-scripts.js"


class SetupTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="flx4-setup-")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.repo = self.root / "repository with spaces"
        self.repo.mkdir()
        self.home = self.root / "home with spaces"
        self.home.mkdir()
        shutil.copy2(REPO / "setup-mixxx-links.sh", self.repo)
        for directory in ("controllers", "effects"):
            shutil.copytree(REPO / directory, self.repo / directory)
        self.targets = [self.home / profile / "controllers" / EXTENDED_XML
                        for profile in (".mixxx", ".mixxx-test")]
        self.source = self.repo / "controllers" / BASIC_XML

    def run_setup(self, *arguments, success=True):
        sources = {path: path.read_bytes() for path in (self.repo / "controllers").iterdir()
                   if path.is_file()}
        result = subprocess.run(
            ["bash", str(self.repo / "setup-mixxx-links.sh"), *arguments],
            env=dict(os.environ, HOME=str(self.home)), cwd=self.root,
            capture_output=True, text=True,
        )
        self.assertEqual(result.returncode == 0, success, result.stdout + result.stderr)
        for path, content in sources.items():
            self.assertEqual(path.read_bytes(), content, f"Source changed: {path}")
        return result

    def test_default_links_only_and_preserves_existing_behavior(self):
        controller_dir = self.targets[0].parent
        controller_dir.mkdir(parents=True)
        foreign = controller_dir / BASIC_SCRIPT
        foreign.write_text("existing user script")
        basic_link = controller_dir / BASIC_XML
        basic_link.symlink_to(self.root / "old-missing-target")
        result = self.run_setup()
        self.assertIn("[WARN]", result.stderr)
        self.assertEqual(foreign.read_text(), "existing user script")
        for profile in (".mixxx", ".mixxx-test"):
            for directory in ("controllers", "effects"):
                for source in (self.repo / directory).rglob("*"):
                    if source.is_file():
                        target = self.home / profile / directory / source.relative_to(
                            self.repo / directory)
                        if target == foreign:
                            continue
                        self.assertTrue(target.is_symlink(), target)
                        self.assertEqual(target.readlink(), source)
        self.assertTrue(all(not target.exists() for target in self.targets))

    def test_extended_xml_names_order_and_mapping_content(self):
        self.run_setup("--extended-copy")
        basic = ET.parse(self.source).getroot()
        self.assertEqual(basic.findtext("info/name"), "Pioneer DDJ-FLX4 (Basic)")
        for target in self.targets:
            self.assertTrue(target.is_file())
            self.assertFalse(target.is_symlink())
            self.assertIn(b"<!-- Generated by setup-mixxx-links.sh: extended-copy v1.",
                          target.read_bytes())
            extended = ET.parse(target).getroot()
            self.assertEqual(extended.findtext("info/name"), "Pioneer DDJ-FLX4 (Extended)")
            scripts = extended.findall("controller/scriptfiles/file")
            self.assertEqual([script.attrib for script in scripts], [
                {"filename": BASIC_SCRIPT, "functionprefix": "PioneerDDJFLX4"},
                {"filename": EXTENDED_SCRIPT, "functionprefix": ""},
            ])
            # Undo the two intended XML changes and compare the remaining mapping.
            extended.find("info/name").text = basic.findtext("info/name")
            extended.find("controller/scriptfiles").remove(scripts[1])
            scripts[0].tail = basic.find("controller/scriptfiles/file").tail
            self.assertEqual(ET.tostring(extended), ET.tostring(basic))
            self.assertIn(b"BROWSER Section START", target.read_bytes())
            basic_link = target.parent / BASIC_XML
            self.assertTrue(basic_link.is_symlink())
            self.assertEqual(basic_link.readlink(), self.source)
        self.assertEqual(self.targets[0].read_bytes(), self.targets[1].read_bytes())

    def test_repeated_run_refreshes_generated_copies(self):
        self.run_setup("--extended-copy")
        before = self.targets[0].read_bytes()
        self.run_setup("--extended-copy")
        self.assertEqual(self.targets[0].read_bytes(), before)
        self.source.write_text(self.source.read_text().replace(
            "Community-maintained Basic", "Updated Basic"))
        self.run_setup("--extended-copy")
        for target in self.targets:
            self.assertNotEqual(target.read_bytes(), before)
            self.assertIn("Updated Basic", ET.parse(target).findtext("info/description"))
        before = [target.read_bytes() for target in self.targets]
        self.run_setup()
        self.assertEqual([target.read_bytes() for target in self.targets], before)

    def test_foreign_file_blocks_updates_in_both_profiles(self):
        self.run_setup("--extended-copy")
        before = self.targets[0].read_bytes()
        foreign = b"foreign XML without ownership marker"
        self.targets[1].write_bytes(foreign)
        self.source.write_text(self.source.read_text().replace(
            "Community-maintained Basic", "Updated Basic"))
        result = self.run_setup("--extended-copy", success=False)
        self.assertIn("foreign file left unchanged", result.stderr)
        self.assertEqual(self.targets[0].read_bytes(), before)
        self.assertEqual(self.targets[1].read_bytes(), foreign)

    def test_symlinks_and_directories_are_never_replaced(self):
        self.run_setup("--extended-copy")
        generated = self.targets[1].read_bytes()
        victim = self.root / "victim.xml"
        victim.write_bytes(generated)
        for kind in ("owned-file-link", "dangling-link", "directory"):
            with self.subTest(kind=kind):
                target = self.targets[0]
                target.unlink()
                if kind == "directory":
                    target.mkdir()
                else:
                    destination = victim if kind == "owned-file-link" else self.root / "missing"
                    target.symlink_to(destination)
                result = self.run_setup("--extended-copy", success=False)
                self.assertIn("left unchanged", result.stderr)
                self.assertEqual(victim.read_bytes(), generated)
                self.assertEqual(self.targets[1].read_bytes(), generated)
                if kind == "directory":
                    self.assertTrue(target.is_dir())
                    target.rmdir()
                else:
                    self.assertEqual(target.readlink(), destination)
                    target.unlink()
                target.write_bytes(generated)

    def test_invalid_arguments_have_no_installation_side_effects(self):
        for arguments in (("--unknown",), ("--extended-copy", "extra"),
                          ("--extended-copy", "--extended-copy"), ("",)):
            with self.subTest(arguments=arguments):
                result = self.run_setup(*arguments, success=False)
                self.assertIn("Usage:", result.stderr)
                self.assertEqual(list(self.home.iterdir()), [])

    def test_missing_sources_are_reported(self):
        for filename in (BASIC_XML, BASIC_SCRIPT, EXTENDED_SCRIPT):
            with self.subTest(filename=filename):
                source = self.repo / "controllers" / filename
                content = source.read_bytes()
                source.unlink()
                result = self.run_setup("--extended-copy", success=False)
                self.assertIn(f"Missing source file: {source}", result.stderr)
                self.assertTrue(all(not target.exists() for target in self.targets))
                source.write_bytes(content)

    def test_invalid_or_unexpected_xml_is_rejected(self):
        original = self.source.read_text()
        invalid_templates = [
            "<broken",
            original.replace("MixxxControllerPreset", "UnexpectedRoot"),
            original.replace("Pioneer DDJ-FLX4 (Basic)", "Unexpected name"),
            original.replace("<name>", "<unexpected>").replace("</name>", "</unexpected>"),
            original.replace("<controller id=", '<controller /><controller id='),
            original.replace("<scriptfiles>", "<scriptfiles /><scriptfiles>"),
            original.replace("scriptfiles", "unexpected"),
            original.replace(BASIC_SCRIPT, "missing.script.js"),
            original.replace('functionprefix="PioneerDDJFLX4"', 'functionprefix=""'),
            original.replace("</scriptfiles>", '<file filename="extra.js" /></scriptfiles>'),
        ]
        for index, template in enumerate(invalid_templates):
            with self.subTest(template=index):
                self.source.write_text(template)
                result = self.run_setup("--extended-copy", success=False)
                self.assertIn("[ERROR] Extended copy:", result.stderr)
                self.assertTrue(all(not target.exists() for target in self.targets))


if __name__ == "__main__":
    unittest.main(verbosity=2)
